# Generated by Django 4.1.4 on 2022-12-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0001_initial'),
        ('bigcat', '0002_bigcat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigcat',
            name='habitat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habitat', to='habitats.habitat'),
            preserve_default=False,
        ),
    ]
